name: basic_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # run tests
      - name: Run black
        run: |
          python -m pip install black
          black .
      - name: Run isort
        run: |
          python -m pip install isort
          isort .
      - name: Run bandit
        run: |
          python -m pip install bandit
          bandit -r . --exit-zero
      - name: Run safety
        run: |
          python -m pip install safety
          safety check --full-report
